##  Trabajo en clase
Importar el csv con la columna data como indice y hacerla datetime

In [8]:
import pandas as pd

In [7]:
f = "../data/001_raw/ClimaLab_2025-08-05_2026-08-05.csv"
esolmet = pd.read_csv(f,index_col="date",parse_dates=True)
esolmet.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 526671 entries, 2025-08-05 00:00:00 to 2026-08-05 18:04:00
Data columns (total 10 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   dhi       526395 non-null  float64
 1   dni       519439 non-null  float64
 2   ghi       526638 non-null  float64
 3   p_atm     318166 non-null  float64
 4   rain_acc  526671 non-null  float64
 5   rh        525610 non-null  float64
 6   tdb       526671 non-null  float64
 7   uv        526671 non-null  float64
 8   wd        526671 non-null  float64
 9   ws        526671 non-null  float64
dtypes: float64(10)
memory usage: 44.2 MB

In [9]:
esolmet.columns

Index(['dhi', 'dni', 'ghi', 'p_atm', 'rain_acc', 'rh', 'tdb', 'uv', 'wd',
       'ws'],
      dtype='str')

In [10]:
esolmet.index

DatetimeIndex(['2025-08-05 00:00:00', '2025-08-05 00:01:00',
               '2025-08-05 00:02:00', '2025-08-05 00:03:00',
               '2025-08-05 00:04:00', '2025-08-05 00:05:00',
               '2025-08-05 00:06:00', '2025-08-05 00:07:00',
               '2025-08-05 00:08:00', '2025-08-05 00:09:00',
               ...
               '2026-08-05 17:55:00', '2026-08-05 17:56:00',
               '2026-08-05 17:57:00', '2026-08-05 17:58:00',
               '2026-08-05 17:59:00', '2026-08-05 18:00:00',
               '2026-08-05 18:01:00', '2026-08-05 18:02:00',
               '2026-08-05 18:03:00', '2026-08-05 18:04:00'],
              dtype='datetime64[us]', name='date', length=526671, freq=None)

In [12]:
esolmet.columns

Index(['dhi', 'dni', 'ghi', 'p_atm', 'rain_acc', 'rh', 'tdb', 'uv', 'wd',
       'ws'],
      dtype='str')

In [14]:
esolmet.tdb

date
2025-08-05 00:00:00    18.62
2025-08-05 00:01:00    18.67
2025-08-05 00:02:00    18.72
2025-08-05 00:03:00    18.74
2025-08-05 00:04:00    18.76
                       ...
2026-08-05 18:00:00    31.67
2026-08-05 18:01:00    31.65
2026-08-05 18:02:00    31.63
2026-08-05 18:03:00    31.57
2026-08-05 18:04:00    31.53
Name: tdb, Length: 526671, dtype: float64

In [15]:
esolmet["tdb"]

date
2025-08-05 00:00:00    18.62
2025-08-05 00:01:00    18.67
2025-08-05 00:02:00    18.72
2025-08-05 00:03:00    18.74
2025-08-05 00:04:00    18.76
                       ...
2026-08-05 18:00:00    31.67
2026-08-05 18:01:00    31.65
2026-08-05 18:02:00    31.63
2026-08-05 18:03:00    31.57
2026-08-05 18:04:00    31.53
Name: tdb, Length: 526671, dtype: float64

In [16]:
esolmet["tdb"]

date
2025-08-05 00:00:00    18.62
2025-08-05 00:01:00    18.67
2025-08-05 00:02:00    18.72
2025-08-05 00:03:00    18.74
2025-08-05 00:04:00    18.76
                       ...
2026-08-05 18:00:00    31.67
2026-08-05 18:01:00    31.65
2026-08-05 18:02:00    31.63
2026-08-05 18:03:00    31.57
2026-08-05 18:04:00    31.53
Name: tdb, Length: 526671, dtype: float64

In [18]:
esolmet[["tdb","ghi"]]

                       tdb    ghi
date
2025-08-05 00:00:00  18.62    0.0
2025-08-05 00:01:00  18.67    0.0
2025-08-05 00:02:00  18.72    0.0
2025-08-05 00:03:00  18.74    0.0
2025-08-05 00:04:00  18.76    0.0
...                    ...    ...
2026-08-05 18:00:00  31.67  134.4
2026-08-05 18:01:00  31.65  129.3
2026-08-05 18:02:00  31.63  120.0
2026-08-05 18:03:00  31.57  103.1
2026-08-05 18:04:00  31.53   86.8

[526671 rows x 2 columns]

In [19]:
esolmet[["dhi"]]

                       dhi
date
2025-08-05 00:00:00   0.00
2025-08-05 00:01:00   0.00
2025-08-05 00:02:00   0.00
2025-08-05 00:03:00   0.00
2025-08-05 00:04:00   0.00
...                    ...
2026-08-05 18:00:00  80.60
2026-08-05 18:01:00  76.32
2026-08-05 18:02:00  71.56
2026-08-05 18:03:00  67.43
2026-08-05 18:04:00  63.86

[526671 rows x 1 columns]

In [22]:
bhi = esolmet.ghi - esolmet.dhi 
bhi

date
2025-08-05 00:00:00     0.00
2025-08-05 00:01:00     0.00
2025-08-05 00:02:00     0.00
2025-08-05 00:03:00     0.00
2025-08-05 00:04:00     0.00
                       ...
2026-08-05 18:00:00    53.80
2026-08-05 18:01:00    52.98
2026-08-05 18:02:00    48.44
2026-08-05 18:03:00    35.67
2026-08-05 18:04:00    22.94
Length: 526671, dtype: float64

In [24]:
esolmet["bhi"] = esolmet.ghi - esolmet.dhi 
esolmet

,dhi,dni,ghi,p_atm,rain_acc,rh,tdb,uv,wd,ws,bhi
date,,,,,,,,,,,
2025-08-05 00:00:00,0.00,0.00,0.0,867.6984,0.0,99.60,18.62,0.000,34.36,0.800,0.00
2025-08-05 00:01:00,0.00,0.00,0.0,867.6693,0.0,100.00,18.67,0.000,16.16,0.525,0.00
2025-08-05 00:02:00,0.00,0.00,0.0,867.6098,0.0,100.00,18.72,0.000,31.93,0.000,0.00
2025-08-05 00:03:00,0.00,0.00,0.0,867.5547,0.0,100.00,18.74,0.000,43.91,0.413,0.00
2025-08-05 00:04:00,0.00,0.00,0.0,867.5483,0.0,100.00,18.76,0.000,30.31,0.175,0.00
...,...,...,...,...,...,...,...,...,...,...,...
2026-08-05 18:00:00,80.60,99.40,134.4,860.0803,0.0,36.90,31.67,0.007,122.10,0.938,53.80
2026-08-05 18:01:00,76.32,103.90,129.3,860.0957,0.0,37.13,31.65,0.006,68.51,1.275,52.98
2026-08-05 18:02:00,71.56,97.50,120.0,860.1653,0.0,37.18,31.63,0.006,113.40,1.012,48.44
2026-08-05 18:03:00,67.43,58.72,103.1,860.1698,0.0,37.70,31.57,0.006,184.70,1.775,35.67
2026-08-05 18:04:00,63.86,23.00,86.8,860.1932,0.0,37.44,31.53,0.005,123.40,0.987,22.94

In [25]:
esolmet.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 526671 entries, 2025-08-05 00:00:00 to 2026-08-05 18:04:00
Data columns (total 11 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   dhi       526395 non-null  float64
 1   dni       519439 non-null  float64
 2   ghi       526638 non-null  float64
 3   p_atm     318166 non-null  float64
 4   rain_acc  526671 non-null  float64
 5   rh        525610 non-null  float64
 6   tdb       526671 non-null  float64
 7   uv        526671 non-null  float64
 8   wd        526671 non-null  float64
 9   ws        526671 non-null  float64
 10  bhi       526362 non-null  float64
dtypes: float64(11)
memory usage: 48.2 MB

In [26]:
esolmet.describe()

,dhi,dni,ghi,p_atm,rain_acc,rh,tdb,uv,wd,ws,bhi
count,526395.000000,519439.000000,526638.000000,318166.000000,526671.000000,525610.000000,526671.000000,526671.000000,526671.000000,526671.000000,526362.000000
mean,84.682566,245.428518,259.868756,855.764764,0.544726,61.357315,23.687725,0.050666,203.610428,1.718627,175.235759
std,141.004714,334.928735,352.382120,17.700092,3.867761,21.927014,4.516988,0.074867,113.332804,1.052454,274.919996
min,0.000000,0.000000,0.000000,800.001000,0.000000,12.060000,10.820000,0.000000,0.000000,0.000000,-203.000000
25%,0.000000,0.000000,0.000000,859.158250,0.000000,44.060000,20.030000,0.000000,119.200000,1.050000,0.000000
50%,1.079000,0.000000,2.785000,862.758400,0.000000,59.060000,23.520000,0.001000,203.500000,1.688000,0.000000
75%,124.200000,598.700000,535.000000,865.283675,0.000000,77.790000,27.060000,0.095000,323.100000,2.300000,296.300000
max,1208.000000,1370.000000,1492.000000,899.677700,56.900000,100.000000,38.590000,0.691000,351.700000,13.710000,1045.800000

In [33]:
str(esolmet.ghi)

'date\n2025-08-05 00:00:00      0.0\n2025-08-05 00:01:00      0.0\n2025-08-05 00:02:00      0.0\n2025-08-05 00:03:00      0.0\n2025-08-05 00:04:00      0.0\n                       ...  \n2026-08-05 18:00:00    134.4\n2026-08-05 18:01:00    129.3\n2026-08-05 18:02:00    120.0\n2026-08-05 18:03:00    103.1\n2026-08-05 18:04:00     86.8\nName: ghi, Length: 526671, dtype: float64'

In [34]:
esolmet.ghi.astype(str)

date
2025-08-05 00:00:00      0.0
2025-08-05 00:01:00      0.0
2025-08-05 00:02:00      0.0
2025-08-05 00:03:00      0.0
2025-08-05 00:04:00      0.0
                       ...
2026-08-05 18:00:00    134.4
2026-08-05 18:01:00    129.3
2026-08-05 18:02:00    120.0
2026-08-05 18:03:00    103.1
2026-08-05 18:04:00     86.8
Name: ghi, Length: 526671, dtype: str

In [35]:
esolmet["ghi_str"] = esolmet.ghi.astype(str)

In [36]:
esolmet

,dhi,dni,ghi,p_atm,rain_acc,rh,tdb,uv,wd,ws,bhi,ghi_str
date,,,,,,,,,,,,
2025-08-05 00:00:00,0.00,0.00,0.0,867.6984,0.0,99.60,18.62,0.000,34.36,0.800,0.00,0.0
2025-08-05 00:01:00,0.00,0.00,0.0,867.6693,0.0,100.00,18.67,0.000,16.16,0.525,0.00,0.0
2025-08-05 00:02:00,0.00,0.00,0.0,867.6098,0.0,100.00,18.72,0.000,31.93,0.000,0.00,0.0
2025-08-05 00:03:00,0.00,0.00,0.0,867.5547,0.0,100.00,18.74,0.000,43.91,0.413,0.00,0.0
2025-08-05 00:04:00,0.00,0.00,0.0,867.5483,0.0,100.00,18.76,0.000,30.31,0.175,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-05 18:00:00,80.60,99.40,134.4,860.0803,0.0,36.90,31.67,0.007,122.10,0.938,53.80,134.4
2026-08-05 18:01:00,76.32,103.90,129.3,860.0957,0.0,37.13,31.65,0.006,68.51,1.275,52.98,129.3
2026-08-05 18:02:00,71.56,97.50,120.0,860.1653,0.0,37.18,31.63,0.006,113.40,1.012,48.44,120.0
2026-08-05 18:03:00,67.43,58.72,103.1,860.1698,0.0,37.70,31.57,0.006,184.70,1.775,35.67,103.1
2026-08-05 18:04:00,63.86,23.00,86.8,860.1932,0.0,37.44,31.53,0.005,123.40,0.987,22.94,86.8

In [28]:
esolmet.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 526671 entries, 2025-08-05 00:00:00 to 2026-08-05 18:04:00
Data columns (total 12 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   dhi       526395 non-null  float64
 1   dni       519439 non-null  float64
 2   ghi       526638 non-null  float64
 3   p_atm     318166 non-null  float64
 4   rain_acc  526671 non-null  float64
 5   rh        525610 non-null  float64
 6   tdb       526671 non-null  float64
 7   uv        526671 non-null  float64
 8   wd        526671 non-null  float64
 9   ws        526671 non-null  float64
 10  bhi       526362 non-null  float64
 11  ghi_str   526671 non-null  str
dtypes: float64(11), str(1)
memory usage: 52.2 MB

In [29]:
# esolmet.to_csv()

ValueError: zip() argument 2 is shorter than argument 1

In [31]:
f = "../data/002_intermediate/esolmet_dhi_ghi_str.csv"
esolmet.to_csv(f)